### ISSUE TITLE
Bug: Long Commands overwrite text on same line (bash/zsh)

### ISSUE THREAD

**Issue by kunalmohan** [mosaic-org/mosaic#105]
A long command overwrites the characters in the starting of the same line, instead of the new line.

![mosaic-bug](https://user-images.githubusercontent.com/44079328/102335208-9b2d4d80-3fb5-11eb-831d-dca26de10b59.png)

Steps to reproduce-
Type a long enough text in the bash shell.

**Comment by henil** [comment]
I am able to reproduce it in `bash` and `zsh` but not in `fish`.

So just to highlight can you add bash/zsh in the title.

**Comment by imsnif** [comment]
This should be solved in main. Could you please confirm?

**Comment by kunalmohan** [comment]
Yep, its fixed now. Thanks!
