### ISSUE TITLE
Compatibility, neovim, nerd tree

### ISSUE THREAD

**Issue by denismaxim0v** [mosaic-org/mosaic#110]
So if you open neovim and then nerd_tree with ```e .```
 - select a file
 - open it(won't show from line 1)
 - open nerd_tree again(glitch happens)
 
 If you scroll up and down, it updates and you see nerd_tree normally
 Happens with files that have long lines
 
![Screenshot from 2020-12-18 11-29-53](https://user-images.githubusercontent.com/11789381/102598602-f16cce80-4124-11eb-8b6b-3f462f24beb2.png)
![Screenshot from 2020-12-18 11-30-06](https://user-images.githubusercontent.com/11789381/102598604-f2056500-4124-11eb-8f73-a1e8ec69d565.png)
[mosaic-3.log](https://github.com/mosaic-org/mosaic/files/5714877/mosaic-3.log)

**Comment by imsnif** [comment]
@denismaxim0v - I just merged a fix for this, could you please check?

**Comment by denismaxim0v** [comment]
> @denismaxim0v - I just merged a fix for this, could you please check?

This one is now good too
