### ISSUE TITLE
Compatibility neovim, open up a new line following the current line and add text there, delete current line

### ISSUE THREAD

**Issue by denismaxim0v** [mosaic-org/mosaic#111]
- open neovim
 - open a file
 - go to any line
 - press o to open a new line following the current line
 Moves the line down, hides the line number.
EDIT: Happens if you delete the current line as well
![Screenshot from 2020-12-18 11-42-06](https://user-images.githubusercontent.com/11789381/102599625-68ef2d80-4126-11eb-92cc-5b290610711a.png)

**Comment by imsnif** [comment]
@denismaxim0v - I just merged a fix for this, could you please check?

**Comment by denismaxim0v** [comment]
> @denismaxim0v - I just merged a fix for this, could you please check?

All is perfect
