### ISSUE TITLE
Bug: Deleting a multiline command deletes the previous line.

### ISSUE THREAD

**Issue by kunalmohan** [mosaic-org/mosaic#114]
This is on bash.

![mosaic-bug](https://user-images.githubusercontent.com/44079328/102625413-77136d00-416b-11eb-9f38-f85820eb11e3.gif)

**Comment by kunalmohan** [comment]
Oops..just tested this with changes in #112. This will be fixed by that PR.

**Comment by imsnif** [comment]
Just merged it. :) Shall we close?
