### ISSUE TITLE
Bug: Weird behavior while running a series of npm commands

### ISSUE THREAD

**Issue by kunalmohan** [mosaic-org/mosaic#117]
I have included the video files for a better explanation. Both the videos were recorded under mosaic.

1. A simple npm init command works perfectly fine under mosaic.
![exptd](https://user-images.githubusercontent.com/44079328/102745425-f5e1f300-4381-11eb-802f-0180667b9c0f.gif)

2. However, after running an npm server on a terminal, `npm init` has weird behavior on the same terminal.
![act](https://user-images.githubusercontent.com/44079328/102745438-fd090100-4381-11eb-858e-4171ca6dfa82.gif)

This is on bash.

**Comment by imsnif** [comment]
Nice find! I think this should now be fixed in main. Could you please check, @kunalmohan ?

**Comment by kunalmohan** [comment]
Yep, this is fixed now. Thanks!

Fixed by #137
