### ISSUE TITLE
mac use-ability

### ISSUE THREAD

**Issue by qballer** [mosaic-org/mosaic#12]
I've been testing (playing?) with Mosaic in my mac machine in the last couple of days. I even created silly #11 to workaround mosaic not running in mac and I've seen several issues:

- arrow keys don't seem to work inside vim 
- vim rendering looks somewhat worse from what is shown in @imsnif working machine. 
- I get a  few exceptions here and there 
- htop issue while running it, which is common to Linux as well. 

This makes sense in the early phases of the project. I'm going to try and work on mac and will document the process here.
there is also the question of making the CMD key the default leader. I'm amazed it run with such little changes, which is very cool. I'm mainly communicating here because some errors are general and some not, some concerns are more of UX rather than anything else.

**Comment by imsnif** [comment]
@qballer - can you check the vim rendering issue with what's currently on main? I issued some fixes and think they might have helped.

**Comment by imsnif** [comment]
I think most of these have been addressed elsewhere.
