### ISSUE TITLE
Compatibility (Neovim): Glitches in wrapped text rendering and cursor position

### ISSUE THREAD

**Issue by kunalmohan** [mosaic-org/mosaic#123]
![mosaic-neovim](https://user-images.githubusercontent.com/44079328/103122482-7700f900-46a6-11eb-9d23-ccb04e41c1b5.png)

Text that wraps to a new line is followed by a number of empty lines (the number of empty lines changes when scrolling up and down.

After the cursor reaches the topmost line, pressing `K` takes the cursor to the neovim command palette (at the bottom) and messes up the line numbers as well (visible in screenshot, line numbers are relative).

Shell background color is blue.
Neovim background color is black.

**Comment by imsnif** [comment]
I think this should now be fixed. Could you please check, @kunalmohan ?

**Comment by kunalmohan** [comment]
@imsnif Thanks! This issue is now fixed. But I see a couple of new bugs now. I'll create a new issue for them.

**Comment by kunalmohan** [comment]
Fixed by #137
