### ISSUE TITLE
Compatibility (Neovim): Color on resize and cursor position on exit

### ISSUE THREAD

**Issue by kunalmohan** [mosaic-org/mosaic#139]
![mosaicbug](https://user-images.githubusercontent.com/44079328/104299074-c2126d00-54ea-11eb-8094-4e9ce91954a7.gif)

As can be seen, a resize event in neovim changes the background color. 

The cursor position after exit is wrong. On typing the characters of `"nvim src/main.rs"` are being overwritten.

This is on bash.

**Comment by imsnif** [comment]
@kunalmohan - it says "Video can't be displayed because the file is corrupt" here on github. Does it display it properly for you?

**Comment by kunalmohan** [comment]
Yep, it was displaying it properly for me. Nevertheless, I have replaced it with a gif now.

**Comment by imsnif** [comment]
Thanks!

**Comment by imsnif** [comment]
@kunalmohan - I fixed the first issue with the coloring, could you please check?

About the second issue: does this happen consistently for you? I could only reproduce it part of the times, and I think this is due to a race condition that I'm planning on addressing next. I just want to make sure it's the same thing?

**Comment by kunalmohan** [comment]
@imsnif the first issue is fixed. Thank You!

You're the second one. It does not happen consistently, so I guess it's the same thing.

**Comment by imsnif** [comment]
@kunalmohan - I know you're probably very busy right now, so when you have a chance and can check, I think I fixed the second issue.

**Comment by kunalmohan** [comment]
Yep, I checked and was unable to reproduce the issue any more, even intermittently. So, I guess it's fixed. Thank You!
