### ISSUE TITLE
Resizing a terminal window causes all sorts of weird sorcery

### ISSUE THREAD

**Issue by denismaxim0v** [mosaic-org/mosaic#142]
I'll just attach screenshots after multiple terminal window resizes.
![Screenshot from 2021-01-13 07-14-27](https://user-images.githubusercontent.com/11789381/104409610-54f4eb00-556f-11eb-8925-5747013819aa.png)
![Screenshot from 2021-01-13 07-14-52](https://user-images.githubusercontent.com/11789381/104409612-558d8180-556f-11eb-8344-b14589b4c27f.png)
![Screenshot from 2021-01-13 07-15-04](https://user-images.githubusercontent.com/11789381/104409614-558d8180-556f-11eb-8a8a-02bcd51093ca.png)
![Screenshot from 2021-01-13 07-16-14](https://user-images.githubusercontent.com/11789381/104409616-56261800-556f-11eb-9f31-5aaebb9cf99a.png)
[mosaic-3.log](https://github.com/mosaic-org/mosaic/files/5806527/mosaic-3.log)

**Comment by imsnif** [comment]
https://github.com/mosaic-org/mosaic/issues/34 ?

**Comment by denismaxim0v** [comment]
> #34 ?

Is it the same?

**Comment by imsnif** [comment]
I think so? You're talking about window resizes, right? Not pane resizes?

**Comment by denismaxim0v** [comment]
Yes, window resizes

**Comment by imsnif** [comment]
So yes, it's a known issue. But thanks for all the details :) I think @5c077m4n wants to work on this

**Comment by denismaxim0v** [comment]
Other than that, it's really difficult to find new bugs now, which is obviously a good thing. I also can work with mosaic now almost as productively as with tmux 👍

**Comment by imsnif** [comment]
> Other than that, it's really difficult to find new bugs now, which is obviously a good thing. I also can work with mosaic now almost as productively as with tmux +1

That's amazing to hear!! :)
