### ISSUE TITLE
Color resetting issues in Starship prompt

### ISSUE THREAD

**Issue by imsnif** [mosaic-org/mosaic#15]
This was discovered by @TheLostLambda. What happens is that when the prompt has multiple colors, they are not always reset properly (eg. to the default terminal color). I think this happens because there's a bit of a mess right now when we reset named/ansi-code colors (somewhere we probably reset one and not the other).

**Comment by imsnif** [comment]
@TheLostLambda - I think I fixed this in main. Could you check this too? Thanks!

**Comment by TheLostLambda** [comment]
As of this commit:
![image](https://user-images.githubusercontent.com/6251883/98593935-d1e3ba00-22cb-11eb-9ce8-e557c229c2cb.png)

Things still seem broken...

Correct:
![image](https://user-images.githubusercontent.com/6251883/98593986-e758e400-22cb-11eb-9999-bc03f0f9e42a.png)

Bugged (in mosaic):
![image](https://user-images.githubusercontent.com/6251883/98594035-fb9ce100-22cb-11eb-8d1c-3919d19a4c5a.png)

**Comment by qballer** [comment]
I think the colors are a separate issue here. I've seen this in other prompts as well.

**Comment by imsnif** [comment]
@TheLostLambda - there's one commit after this. Could you check with it?

**Comment by TheLostLambda** [comment]
Haha, that's why I posted the commit hash! I was quite suspicious... `git pull` broke somehow and I needed to re-clone the repo, but it's (mostly) better now! I've still got one small irregularity in the colour of the `v0.1.0` bit:

First is the reference, second is mosaic:
![image](https://user-images.githubusercontent.com/6251883/98601395-e5485280-22d6-11eb-911f-7f8802f70b17.png)
![image](https://user-images.githubusercontent.com/6251883/98601380-dc578100-22d6-11eb-9fa9-5e4dfd8423cd.png)

**Comment by imsnif** [comment]
No worries :)

Oi, I don't have that with my prompt :/
Could you help me out by sending me these bytes? https://github.com/mosaic-org/mosaic/blob/main/src/pty_bus.rs#L165
Just append them as chars to a file, so that when you 'cat' the file you see your terminal? I think it'll be easiest for me to debug this like that.

**Comment by imsnif** [comment]
@TheLostLambda - is this still happening?

**Comment by TheLostLambda** [comment]
Just checked, and unfortunately yes :cry: 

I've attached the debug log from my system :)

[prompt-debug.log](https://github.com/mosaic-org/mosaic/files/5612725/prompt-debug.log)

**Comment by imsnif** [comment]
@TheLostLambda - this should be fixed now. I hate ANSI ;P Could you confirm when you have a moment?

**Comment by TheLostLambda** [comment]
It's beautiful! Seems to be working entirely as expected now! Thanks for powering through this!
