### ISSUE TITLE
Document various concepts in the code-base

### ISSUE THREAD

**Issue by imsnif** [mosaic-org/mosaic#22]
There are various concepts from the "terminal world" in the codebase that are not very trivial for developers to immediately understand. It would be good to have a sort of "cheat sheet" document where one could look them up and understand what they mean, as well as where they fit in with the Mosaic project.

@alekspickle - since you rightfully pointed out this issue, I hope you'd be willing to briefly review this document once I write it (hopefully today or tomorrow) and let me know if it makes sense to you.

**Comment by qballer** [comment]
@imsnif Please ping me for a review of that PR, I want to make sure I understand as well :)
