### ISSUE TITLE
MVP - making mosaic public 

### ISSUE THREAD

**Issue by qballer** [mosaic-org/mosaic#3]
exposing mosaic to public development, trying to commit to 01.11.2020:

Primary Goals
- [x] running raw mode application like bandwhich in mosaic
- [x] scrolling inside a pane
- [x] IPC bus
- [x] fix borders 
- [x] possibility to close a pane

Secondary goals:
- [x] github action 
- [x] WIP Readme. 
   - [x] Roadmap 
   - [x] Plugin research goals 
- [x] Org Icon - Done!

**Comment by imsnif** [comment]
We went public, yay!
