### ISSUE TITLE
ctrl+l doesn't clear pane

### ISSUE THREAD

**Issue by qballer** [mosaic-org/mosaic#33]
**Description:**: ctrl+l doesn't work within Mosaic
**Expected behavior**: Clear screen
**Terminal Application**: Iterm2

Mosaic seems to be capturing the ctrl+l but doesn't clear the screen. Could be cool to look into that.

**Comment by imsnif** [comment]
Yeah, ctrl+l is resize-right :( I think we'll fix this once we get the controls figured out.

**Comment by unikzforce** [comment]
is this problem solved? it's marked as complete but i still can see the problem

**Comment by codeRSH** [comment]
Yeah, I was also wondering is there any other keybinding to clear the screen within zellij ?

**Comment by LazyRen** [comment]
JFYI:
Zeelij supports `clear`[^1] action which clears the scrollback buffer of the focused pane.

So adding something similar to below should bind `ctrl+l` to clear the pane.

```
    shared_except "locked" "scroll" "search" {
        bind "Ctrl l" { Clear; }
    }
```
[^1]: https://zellij.dev/documentation/keybindings-possible-actions.html#clear
