### ISSUE TITLE
Mosaic doesn't expand when resizing the terminal window and it panics

### ISSUE THREAD

**Issue by qballer** [mosaic-org/mosaic#38]
OS: mac-os
terminal: alacritty 

When I run Mosaic inside Alaacritty, I get into a situation where mosaic pane size is stuck (and sometimes panics). 

Reconstruct:
- Open Alacritty to not take full-screen area.
- run mosaic
- resize alacritty to full screen 
- notice that Mosaic is still somewhat in original size and doesn't reflow.
- notice that vim didn't stretch after the resize.

<img width="977" alt="Screen Shot 2020-11-10 at 23 45 42" src="https://user-images.githubusercontent.com/1002622/98737531-fe243700-23ae-11eb-96d2-45b52089368e.png">

**Comment by imsnif** [comment]
I think this is: https://github.com/mosaic-org/mosaic/issues/34?

**Comment by qballer** [comment]
I think you are correct.
