### ISSUE TITLE
Refactor: In Screen (src/screen.rs) change internal Winsize to PositionAndSize

### ISSUE THREAD

**Issue by imsnif** [mosaic-org/mosaic#51]
In our Screen, we use libc's Winsize to track the full screen size (as an attribute on screen itself). Now that we have our own struct to track this (PositionAndSize) we should use it instead.

Once we do that, we can merge the two methods on Screen that change its size (namely change_size and change_size_p).

**Comment by denismaxim0v** [comment]
I could take this one if it's still available

**Comment by imsnif** [comment]
Take it away :)
