### ISSUE TITLE
Feature: implement directional change focus

### ISSUE THREAD

**Issue by imsnif** [mosaic-org/mosaic#55]
Implement commands for changing the focus of the pane up/down/right/left.
If there are multiple panes in that direction, it should move to the pane with the most overlapping space.

**Comment by denismaxim0v** [comment]
I could pick this up if no one is working on it

**Comment by imsnif** [comment]
That would be great :)

**Comment by imsnif** [comment]
Implemented. Thanks @denismaxim0v !
