### ISSUE TITLE
Implement Error handling

### ISSUE THREAD

**Issue by imsnif** [mosaic-org/mosaic#61]
Right now we panic when there's an error. Since we do that inside a thread, it's very hard to tell what caused the error. This is especially true if the error we end up getting is an error from another thread that fails to send a message to the panicked thread.

We need some system that would (among other things) allow us to get proper errors across our threads. This will greatly ease development.

**Comment by kunalmohan** [comment]
I would like to work on this issue :smiley:. Will start in a couple of days(as discussed on discord).

**Comment by roee-shapira-tikal** [comment]
@kunalmohan I used [panic::set_hook](https://doc.rust-lang.org/std/panic/fn.set_hook.html) to try and fix this error two of the tests, it might help you too...
