### ISSUE TITLE
htop up and down arrow keys don't work and cause wierd side affect

### ISSUE THREAD

**Issue by qballer** [mosaic-org/mosaic#68]
OS: mac os
terminal app: iterm/Alacritty 

Issue: 

When opening HTOP in mac (confirmed both in Alacritty and iterm2) HTOP doesn't respond to up and down arrow keys.
After exiting HTOP with the q key any typing renders unclear output. The issue only occur if you attempt the up/down keys beforehand
<img width="181" alt="Screen Shot 2020-11-23 at 20 29 44" src="https://user-images.githubusercontent.com/1002622/100002459-3ffca680-2dcd-11eb-8cab-b504651342e8.png">
.

**Comment by imsnif** [comment]
@qballer - does this also happen if you trigger it with up/down keys outside htop?

**Comment by qballer** [comment]
Nope, they work normally (even though the text color has a bug).

**Comment by imsnif** [comment]
Alright, I think I fixed this in main. Could you check and let me know? Also, could you open another issue about the text color? :)

**Comment by qballer** [comment]
right now the side effect isn't happening but the arrow keys still aren't working for me.

**Comment by imsnif** [comment]
Fixed
