### ISSUE TITLE
Feature: Implement tabs

### ISSUE THREAD

**Issue by imsnif** [mosaic-org/mosaic#70]
One should be able to tab between several Screens in an existing session. Each screen can be split into multiple panes.

**Comment by qballer** [comment]
Is the #71 discussion relevant here?

**Comment by imsnif** [comment]
How so?

**Comment by qballer** [comment]
I figured maybe make it a plugin too with the same approach but that sounds overlly complex

**Comment by imsnif** [comment]
I also very much think this should be a core functionality

**Comment by imsnif** [comment]
Implemented in main: https://github.com/mosaic-org/mosaic/pull/89
