### ISSUE TITLE
Feature: Design and implement a status bar

### ISSUE THREAD

**Issue by imsnif** [mosaic-org/mosaic#71]
The status bar can be something like airline, or it can be a new concept. For the time being it should display the shortcuts for the current input mode (showing the user what they can press right now in order to perform actions on the screen and updating itself accordingly).

In the future, it can also contain things like:
* Minimized panes that don't fit on screen
* List of tabs
* System information (through a plugin)
* Other ideas?

**Comment by qballer** [comment]
I think we should provide an API for Plugin creators to place whatever they want there and have in the core only the ability to add stuff to the status bar and listen to events from the status bar (mouse click?). Meaning functional content should go to plugins. What do you think ?

**Comment by imsnif** [comment]
> I think we should provide an API for Plugin creators to place whatever they want there and have in the core only the ability to add stuff to the status bar and listen to events from the status bar (mouse click?). Meaning functional content should go to plugins. What do you think ?

While I agree in principle and think this is definitely the architecturally-right thing to do, I would very much like the users to already have a status bar when they first run the app. And for that status bar to be useful and include things we desperately need right now (eg. what command mode am I in, what shortcuts are available to me and what tabs do I have open). So maybe we can start with having some built-in stuff and then once the plugin system matures consider moving them all to be plugins? Or built-in plugins or some such? What do you think?

**Comment by qballer** [comment]
Since we both agree about the architecture it's more a matter of goals really. What do we prefer, become more user friendly faster or placing the different elements in the right place. I have a suggestion that is somewhere in the middle right now. Develop the status bar as a separate crate. This will allow us to make that crate eventually a plugin when "tiles" mature, and perhaps one of the default plugins we ship with mosaic. This will allow us to consider interface boundaries - AKA, the things we pass in fn calls. This will also allow us to discover more requirements from "tiles".

Your thoughts?

**Comment by imsnif** [comment]
I don't mind this approach. Can we leave it up to the discretion of the implementer? I just don't want to create too big a barrier for contribution here.

**Comment by TheLostLambda** [comment]
Howdy! I'm swooping in to sorta hijack this issue, as I think they whole status bar can now be a plugin! For the MVP, I'm thinking we need just the possible keyboard shortcuts for each mode. This requires a number of problems to be solved:

- [ ] We'll need some sort of concept of a "default" plugin. I might approach this from the perspective of  a "default" layout, that all new tabs are created with
- [ ] We'll need a data directory that default layouts and plugins are installed into. This installation should be performed at build time via `build.rs`
- [ ] Layouts will need an exact size constraint (1 row high, for example)
- [ ] The `Input` plugin instruction will need to be called following *all* keyboard inputs, with a PaneId identifying where the input originated from. A second API function (`handle_global_key`) will be called on key-presses not directed at the plugin.
- [ ] A new API function, `pane_selectable` (or similar) will allow plugins to set their pane as unselectable
- [ ] A new API function, `get_keymap` (or similar) will allow plugins to get a HashTable entry, with the key being the name of the current mode, and the value being a pair of a keyboard shortcut and its binding (this is blocked on the keybinding work from @khs26 probably)

With those prerequisites implemented, the status bar plugin would be part of the default layout and stored in the new data directory. The plugin itself initializes by getting the initial keymap and setting itself as unselectable. It then listens for global key-presses and, if the key pressed was part of the initial keymap, asks for a new keymap. The current keymap will be displayed as nicely as possible in the area available.
