### ISSUE TITLE
Fish + Starship Predictive Autocomplete is Mistyled

### ISSUE THREAD

**Issue by TheLostLambda** [mosaic-org/mosaic#87]
Expected
![image](https://user-images.githubusercontent.com/6251883/101528127-c812ac80-3986-11eb-972f-6be731ca6c28.png)

Actual
![image](https://user-images.githubusercontent.com/6251883/101545682-880bf380-399f-11eb-9d60-32ab1052cf73.png)

We are missing the blue and the dimmed prediction part!

Excitingly, (and perhaps expectedly?) the predicted bit doesn't show up in any logs. The `cat` does, and is blue when I cat the log outside of mosaic, but white inside.

Here is the log with the miscoloured cat: 
[mosaic-3.log](https://github.com/mosaic-org/mosaic/files/5662185/mosaic-3.log)

I honestly have *no* idea what Fish / Starship is doing to render that predicted region...

**Comment by henil** [comment]
So for the record, for me, every command I try to run is colored red and all the subsequent arguments are white. I am also using fish with just a custom prompt. Also for me when I cat the log outside mosaic it is colored properly.

Expected
![1607503267_Dec09_14:11:07](https://user-images.githubusercontent.com/71698300/101605613-69057400-3a28-11eb-9a1b-f5cd1d24338d.png)


Actual
![1607503052_Dec09_14:07:32](https://user-images.githubusercontent.com/71698300/101605233-f0061c80-3a27-11eb-96a1-05f318e48d60.png)

This is the prompt. For some reason mosaic is ignoring the last `set_color normal` and coloring the first command name red. 
```fish
function fish_prompt
    set_color brblack
    echo -n "["(date "+%H:%M")"] "
    set_color blue
    echo -n (hostname)
    if [ $PWD != $HOME ]
        set_color brblack
        echo -n ':'
        set_color yellow
        echo -n (basename $PWD)
    end
    set_color green
    printf '%s ' (__fish_git_prompt)
    set_color red
    echo -n '| '
    set_color normal
end
```

**Comment by imsnif** [comment]
@TheLostLambda - could you try `cat`ing this modified log in your terminal (outside mosaic and then inside) and seeing if it does the expected/wrong thing respectively? I just want to make sure I'm fixing the right thing. :) 
[more-starship.log](https://github.com/mosaic-org/mosaic/files/5665318/more-starship.log)

@henil - I'm not sure this is the same issue. Could you open a separate issue and attach a log by running mosaic with `--debug`?

**Comment by henil** [comment]
@imsnif I think it's that same issue just I have a different(red) color for the first word in the interactive prompt. If I start `fish` with a blank config file I get the same color as @TheLostLambda.

**Comment by TheLostLambda** [comment]
@imsnif Yep! That file looks good outside mosaic, but is all white within!

**Comment by imsnif** [comment]
@TheLostLambda - cool, will work on this now, I think I know what the problem is. Did I mention I hate ANSI? :D
Anyway just FYI: we don't delete the debug log between runs, so everything keeps getting appended to it. To give the most accurate log, quit mosaic immediately after the bug happens then rename the log.

@henil - maybe it is, there can be a lot of different coloring issues. :) I'll work on the original issue and then see if it also fixes yours.

**Comment by imsnif** [comment]
So @henil - I guess you were right after all and this was the same issue (going by your comment in the PR) :)

@TheLostLambda - can you check in main to see if this resolves it for you?

**Comment by TheLostLambda** [comment]
@imsnif Looking great on my terminal, but RIP match statement :laughing: 

Thanks for the quick fix!

**Comment by imsnif** [comment]
> but RIP match statement
Oh damn! I'm sorry, I'm not 100% sure how that happened. I guess speed has its costs. I also left some unneeded self-comments in there I now see. I'll bring it back tomorrow :)

**Comment by TheLostLambda** [comment]
Haha, well, it's slightly reassuring to know that it wasn't intentionally destroyed :laughing: Sounds lovely! No rush though :)
