### ISSUE TITLE
Bug, Compatibility: neovim switching modes

### ISSUE THREAD

**Issue by denismaxim0v** [mosaic-org/mosaic#94]
switching between modes in neovim results in weird glitches.
Steps to reproduce:
 - open a file in neovim
 - move cursor anywhere in the file
 - switch to Insert mode

[mosaic-3.log](https://github.com/mosaic-org/mosaic/files/5673722/mosaic-3.log)

![Screenshot from 2020-12-10 16-36-30](https://user-images.githubusercontent.com/11789381/101790158-cd98ff80-3b0a-11eb-9d0c-b91f4022a7b4.png)

**Comment by imsnif** [comment]
Hey @denismaxim0v, @5c077m4n and I fixed this bug in main. Can you please confirm?

**Comment by denismaxim0v** [comment]
Yup, modes seem to work just fine too
